### ISSUE TITLE
Report shown as empty

### ISSUE THREAD

**Issue by rdb987** [exadel-inc/etoolbox-link-inspector#2]
Report is always empty:

![image](https://user-images.githubusercontent.com/16901319/133767295-11c303f6-d53b-48a7-bd8e-fe833b1bfe0d.png)

Component DataFeedJobExecutor is only satisfied but not active. The bundle is active though:

![image](https://user-images.githubusercontent.com/16901319/133767478-f24186a3-9609-4a98-a8d9-3d7c1b3c4f11.png)

**Comment by adantsou** [comment]
Hi @rdb987,
Thanks for you interest in EToolbox Link Inspector.

The tool uses a data feed generated by the scheduled task instead of calculating data upon each request. Thus this is expected behavior that the report is empty after the tool installation. First of all you should configure the scheduler as described in the "Getting Started" section of README:
>Set up the cron expression and enable the scheduler task at >/system/console/configMgr/com.exadel.etoolbox.linkinspector.core.schedulers.DataFeedGenerationTask

In addition it's recommended to set up the root path for searching broken links, which is /content by default (please see step 2 from the "Getting Started" section):
>Set up the root path for searching broken links at >/system/console/configMgr/com.exadel.etoolbox.linkinspector.core.services.data.impl.GridResourcesGeneratorImpl

As soon as the the scheduler task is completed, the report should be populated with the broken links information.
The progress of the data feed generation is tracked in the log file _crx-quickstart/logs/etoolbox-link-inspector.log_

Hope this clarifies. Please let me know if you have any further questions.

Best Regards

**Comment by rdb987** [comment]
Hello @adantsou , 

Thanks for the clarification.

These are the my current OSGi configurations:

![config-etool-data-feed-generation](https://user-images.githubusercontent.com/16901319/133976037-862d2b0e-b39b-4c33-8b85-c8c9d6935502.png)

And

![grid-resource-generator](https://user-images.githubusercontent.com/16901319/133976061-82be7e2c-2145-4824-b6f2-6ef15eb5a02b.png)

I am expecting the task to be launched every minute but it never starts. I have also tried checking the "Concurrent execution" checkbox but unfortunately didn't help.

Finally, I have also downloaded the source code and deployed manually to my instance. Set breakpoints in active method and there I can debug but it seems the execution never enter the run method. 

Do you have any suggestions?

Thanks in advance, 

Roberto

**Comment by adantsou** [comment]
Hi @rdb987,

The cron expression you specified in the config doesn't look valid. You can use any online service for building a valid cron, e.g. http://www.cronmaker.com

Furthermore, I wouldn't recommend to trigger the task every 1 minute since if there is a lot of content on the instance it might impact the performance (despite the fact that the generation is started as an ordered sling job).

You can use the following cron to trigger the job at the specified time, e.g. every day at 13:15:
`0 15 13 1/1 * ? *`

The following line in the log file _crx-quickstart/logs/etoolbox-link-inspector.log_ indicates that the job started:
`Start broken links collecting, path:`

In addition, it's possible to start links collecting via triggering the servlet http://localhost:4502/content/etoolbox-link-inspector/servlet/triggerDataFeedGeneration, however please note that this should be done for **testing purposes only** and by a user belonging to the _administrators_ group.

Best Regards

**Comment by rdb987** [comment]
Thanks a lot @adantsou , 

It works perfectly now. I did actually generate the chron expression with an online service but you are right it was not recognized. Would be nice to add a warn log in case this happens; in any case, the inspector fits totally our needs.


Roberto

**Comment by adantsou** [comment]
Thanks for your feedback, @rdb987
